name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: iDealOBot
      run: docker build . --file Dockerfile --tag idealobot:$(date +%s)
    - name: Build the Docker image
      working-directory: iDealOBot
      run: docker push idealobot:$(date +%s)


    
